Decision Record Template
Cadasta/decision-records pull request #9
Opened 2017-06-28 18:42 UTC by dpalomino

PR for DR Template

2017-06-28 18:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Cadasta/decision-records?pullRequest=9) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Cadasta/decision-records?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Cadasta/decision-records?pullRequest=9) it.</sub>

2017-06-30 09:58 UTC, oliverroick requested changes
Thanks for getting this started! 

Some thoughts:

- I think, we need some documentation about the whole process itself. It's not 100% clear to me at this point what documents (I'm thinking of the Github ticket, the decision record, wireframes, functional spec) we're creating and where they live. We need to update the [Development process guide wiki page](https://github.com/Cadasta/cadasta-platform/wiki/Development-process-guide). 
- I think we can add a bit more structure. We have two high-level sections: Functional Spec and then Technical spec. All other sections should be one level below.
- I don't understand the difference between "Description of the implemented use cases" and the information that is already being provided in the GitHub ticket. Is it the same; do we just copy the information from the GitHub ticket?
- Should we have a template for the definition of done? A bunch of boxes that always need to be ticket?

2017-07-05 17:14 UTC, dpalomino commented
Thanks a lot @oliverroick for the feedback!

> I think, we need some documentation about the whole process itself. It's not 100% clear to me at this point what documents (I'm thinking of the Github ticket, the decision record, wireframes, functional spec) we're creating and where they live. We need to update the Development process guide wiki page.

Once the DR is approved I can update the wiki, thanks for the heads-up. 

> I think we can add a bit more structure. We have two high-level sections: Functional Spec and then Technical spec. All other sections should be one level below.

Good point. Added in the doc. 

> I don't understand the difference between "Description of the implemented use cases" and the information that is already being provided in the GitHub ticket. Is it the same; do we just copy the information from the GitHub ticket?

It was originally intended to provide a more detailed general explanation about the implementation, but thinking again on this I guess this could be also handled in the "Overview of the suggested solution", so maybe is easier to remove that former one. 

> Should we have a template for the definition of done? A bunch of boxes that always need to be ticket?

Well, I'm not sure if we are going to be able to have a common template for this, as the definition of done could be very different depending on each feature. I was thinking that the definition of done could be a first version of the test case to be included in the Manual test cases spreadsheet. 

Something similar to we were using in the original backlog spreadsheet, like for example (for attaching resources to entities via xforms): 

1. Within a xform, include an image, audio and video resource in location_attributes, party_attributes_default, party_attributes_individual and party_attributes_group
2. Collect the information using geoODK and make sure the resources are included
3. Check that all resources have been properly attached to each entity

What do you think?

2017-07-05 21:47 UTC, bjohare commented
It could probably use an **Introduction** section to set context etc. For example with the permissions DR we should explain the reasons for a refactor in the introduction. This could be as simple as a restatement of the problem/context from the Backlog issue.

2017-07-10 10:22 UTC, oliverroick approved these changes

2017-07-11 09:01 UTC, dpalomino commented
hi @bjohare !
> It could probably use an Introduction section to set context etc. For example with the permissions DR we should explain the reasons for a refactor in the introduction. This could be as simple as a restatement of the problem/context from the Backlog issue.

I think maybe we can handle this in the **Functional Specification** section. In the backlog issue we should have already included the **Problem Statement** (that's the general description of the need trying to cover) and the **Context/Use Case** (typically providing some real examples of these needs). If we need to add more context or overview prior to the **Technical Specification** I think we can use just the **Functional Specification** section in this DR... does it make sense?

2017-09-08 15:44 UTC, oliverroick requested changes
I was about to merge this PR but there are two files now for the DR template this should be cleaned up.

2017-09-18 09:38 UTC, dpalomino commented
Thanks @oliverroick, I didn't notice. I've deleted the initial version that was duplicated, it should be ok now...

2017-09-18 18:51 UTC, amplifi commented on DR_Template.md
> +### Defintion of Done
Typo: should be 'Definition'

2017-09-18 18:52 UTC, amplifi commented on DR_Template.md
>  If the suggested solutions has some costs implications. For instance, AWS costs, licensing, etc.
Typo: should be 'solution'

2017-09-18 18:52 UTC, amplifi commented on DR_Template.md
>  If the suggested solutions has some costs implications. For instance, AWS costs, licensing, etc.
Typo: should be 'solution'

2017-09-18 18:53 UTC, amplifi approved these changes
Aside from two small typos, LGTM

2017-09-21 15:46 UTC, oliverroick approved these changes

2017-09-21 15:47 UTC, merged